# Add configuration values here, as shown below.
#
# pusher_app_id: "2954"
# pusher_key: 7381a978f7dd7f9a1117
# pusher_secret: abdc3b896a0ffb85d373
# stripe_api_key: sk_test_2J0l093xOyW72XUYJHE4Dv2r
# stripe_publishable_key: pk_test_ro9jV5SNwGb1yYlQfzG17LHK
#
# production:
#   stripe_api_key: sk_live_EeHnL644i6zo4Iyq4v1KdV9H
#   stripe_publishable_key: pk_live_9lcthxpSIHbGwmdO941O1XVU

sendinblue_email: 'melanieaugais@gmail.com'
sendinblue_password: JqI50twmhvyGEzZC
sendinblue_api_key: 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
s3_acces_key_id: AKIAI43E2KZJYEEKFNJQ
s3_secret_access_key: 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
